### ISSUE TITLE
GPS got stuck in data acquisition

### ISSUE THREAD

**Issue by MathieuB1** [MathieuB1/KOREK-Lora-GPS_tracker_CubeCell_GPS-6502#1]
Seems an issue when entering in `lowPowerHandler` mode issue

https://github.com/HelTecAutomation/CubeCell-Arduino/issues/230

Seems comming from millis() after lowPowerHandler entered. In my case I fixed the gps to 9600 baud and use my own GPS_Air530Z.h where I removed everything regarding guess gps baudrate.

[https://github.com/MathieuB1/KOREK-Lora-GPS_tracker_CubeCell_GPS-6502/blob/main/GPS_Air530Z1.cpp](url)
[https://github.com/MathieuB1/KOREK-Lora-GPS_tracker_CubeCell_GPS-6502/blob/main/GPS_Air530Z1.h](url)

After fixing the GPS I need also to send a Lora message, and I get stuck there. Will not dig into libs but seems related to Radio.send().

I've finally implemented watchdogs on both to get out of this.

**Comment by MathieuB1** [comment]
Seems not completely solved by removing the double ;; in HardwareSerial.cpp file [#247 (comment)](https://github.com/HelTecAutomation/CubeCell-Arduino/issues/247#issuecomment-1225879764) but we can have some more iterations after using the lowPowerHandler

**Comment by olman011** [comment]
In case anyone is still having this problem, in PlatformIO the solution is to change the platform in the platformio.ini file.
If you choose the Cubecell GPS board when starting a project it will default to "platform = asrmicro650x". This platform is deprecated and must be manually changed to "platform = heltec-cubecell". 
Once this is done the GPS functionality will work correctly.
